package ai.openai.pojo;

/**
 * A completion generated by GPT-3
 * <p>
 * https://beta.openai.com/docs/api-reference/completions/create
 */
public class CompletionChoice {
    /**
     * The generated text. Will include the prompt if
     * {@link CompletionRequest#echo } is true
     */
    private String text;

    /**
     * This index of this completion in the returned list.
     */
    private Integer index;

    /**
     * The log probabilities of the chosen tokens and the top
     * {@link CompletionRequest#logprobs} tokens
     */
    private LogProbResult logprobs;

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    private String finish_reason;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public LogProbResult getLogprobs() {
        return logprobs;
    }

    public void setLogprobs(LogProbResult logprobs) {
        this.logprobs = logprobs;
    }

    public String getFinish_reason() {
        return finish_reason;
    }

    public void setFinish_reason(String finish_reason) {
        this.finish_reason = finish_reason;
    }

    @Override
    public String toString() {
        return "CompletionChoice [text=" + text + ", index=" + index + ", logprobs=" + logprobs + ", finish_reason=" + finish_reason + "]";
    }
}
